-- GymLink 상업 헬스장 카탈로그 확장
-- 앱 번들의 제조사 중립 머신 유형·운동 목록과 Supabase를 동기화한다.

insert into public.machine_catalog
  (code, name_ko, category, provides, is_generative, default_step_kg, aliases, supports_unilateral)
values
  ('CYBEX_EAGLE_LEG_PRESS', 'Cybex Eagle 레그 프레스', 'machine', array['machine_leg_press'], false, 5, array['이글 레그프레스'], false),
  ('CYBEX_EAGLE_LEG_EXT', 'Cybex Eagle 레그 익스텐션', 'machine', array['machine_leg_ext'], false, 5, array['이글 레그익스텐션'], false),
  ('CYBEX_EAGLE_SEATED_CURL', 'Cybex Eagle 시티드 레그 컬', 'machine', array['machine_leg_curl','machine_leg_curl_seated'], false, 5, array['이글 시티드컬'], false),
  ('CYBEX_EAGLE_PRONE_CURL', 'Cybex Eagle 프론 레그 컬', 'machine', array['machine_leg_curl','machine_leg_curl_prone'], false, 5, array['이글 프론컬'], false),
  ('CYBEX_EAGLE_CALF', 'Cybex Eagle 카프', 'machine', array['machine_calf'], false, 5, array['이글 카프'], false),
  ('CYBEX_EAGLE_HIP_AB_AD', 'Cybex Eagle 힙 어브덕션·어덕션', 'machine', array['machine_hip_abd','machine_hip_add'], false, 5, array['이글 힙'], false),
  ('CYBEX_EAGLE_GLUTE', 'Cybex Eagle 글루트', 'machine', array['machine_glute','machine_glute_kickback'], false, 5, array['이글 글루트'], true),
  ('CYBEX_EAGLE_CHEST', 'Cybex Eagle 체스트 프레스', 'machine', array['machine_chest_press'], false, 5, array['이글 체스트'], true),
  ('CYBEX_EAGLE_INCLINE', 'Cybex Eagle 인클라인 프레스', 'machine', array['machine_incline_press'], false, 5, array['이글 인클라인'], true),
  ('CYBEX_EAGLE_OVERHEAD', 'Cybex Eagle 오버헤드 프레스', 'machine', array['machine_shoulder_press'], false, 5, array['이글 숄더'], true),
  ('CYBEX_EAGLE_PULLDOWN', 'Cybex Eagle 랫 풀다운', 'machine', array['machine_lat_pulldown'], false, 5, array['이글 풀다운'], true),
  ('CYBEX_EAGLE_INCLINE_PULL', 'Cybex Eagle 인클라인 풀', 'machine', array['machine_incline_pull','machine_high_row'], false, 5, array['이글 인클라인풀'], true),
  ('CYBEX_EAGLE_ROW', 'Cybex Eagle 로우', 'machine', array['machine_row'], false, 5, array['이글 로우'], true),
  ('CYBEX_EAGLE_ARM_CURL', 'Cybex Eagle 암 컬', 'machine', array['machine_biceps'], false, 5, array['이글 암컬'], false),
  ('CYBEX_EAGLE_ARM_EXT', 'Cybex Eagle 암 익스텐션', 'machine', array['machine_triceps_extension'], false, 5, array['이글 암익스텐션'], false),
  ('CYBEX_EAGLE_FLY_REAR', 'Cybex Eagle 플라이·리어 델트', 'machine', array['machine_pec_deck','machine_rear_delt'], false, 5, array['이글 플라이'], false),
  ('CYBEX_EAGLE_LATERAL', 'Cybex Eagle 래터럴 레이즈', 'machine', array['machine_lateral_raise'], false, 5, array['이글 래터럴'], false),
  ('CYBEX_EAGLE_AB', 'Cybex Eagle 앱도미널', 'machine', array['machine_ab'], false, 5, array['이글 앱도미널'], false),
  ('CYBEX_EAGLE_BACK_EXT', 'Cybex Eagle 백 익스텐션', 'machine', array['machine_back_ext'], false, 5, array['이글 백익스텐션'], false),
  ('CYBEX_EAGLE_TORSO', 'Cybex Eagle 토르소 로테이션', 'machine', array['machine_torso_rotation'], false, 5, array['이글 토르소'], false),
  ('PENDULUM_SQUAT', '펜듈럼 스쿼트', 'machine', array['machine_pendulum_squat'], false, 5, '{}', false),
  ('BELT_SQUAT', '벨트 스쿼트', 'machine', array['machine_belt_squat'], false, 5, '{}', false),
  ('V_SQUAT', 'V 스쿼트', 'machine', array['machine_v_squat'], false, 10, '{}', false),
  ('SISSY_SQUAT', '시시 스쿼트', 'machine', array['machine_sissy_squat'], false, null, '{}', false),
  ('LEG_PRESS_45', '45도 레그 프레스', 'machine', array['machine_leg_press','machine_leg_press_45'], false, 10, '{}', false),
  ('LEG_PRESS_HORIZONTAL', '수평 레그 프레스', 'machine', array['machine_leg_press','machine_leg_press_horizontal'], false, 5, '{}', false),
  ('STANDING_LEG_CURL', '스탠딩 원레그 컬', 'machine', array['machine_leg_curl','machine_leg_curl_standing'], false, 5, '{}', true),
  ('GLUTE_KICKBACK', '글루트 킥백 머신', 'machine', array['machine_glute_kickback'], false, 5, '{}', true),
  ('ADDUCTOR', '힙 어덕션 머신', 'machine', array['machine_hip_add'], false, 5, '{}', false),
  ('ABDUCTOR', '힙 어브덕션 머신', 'machine', array['machine_hip_abd'], false, 5, '{}', false),
  ('INCLINE_PRESS_M', '인클라인 체스트 프레스', 'machine', array['machine_incline_press'], false, 5, '{}', false),
  ('DECLINE_PRESS_M', '디클라인 체스트 프레스', 'machine', array['machine_decline_press'], false, 5, '{}', false),
  ('HIGH_ROW_M', '하이 로우 머신', 'machine', array['machine_high_row'], false, 5, '{}', true),
  ('LOW_ROW_M', '로우 로우 머신', 'machine', array['machine_low_row'], false, 5, '{}', true),
  ('PULLOVER_M', '풀오버 머신', 'machine', array['machine_pullover'], false, 5, '{}', false),
  ('PREACHER_CURL_M', '프리처 컬 머신', 'machine', array['machine_biceps_preacher'], false, 5, '{}', false),
  ('DIP_PRESS_M', '딥 프레스 머신', 'machine', array['machine_dip_press'], false, 5, '{}', false),
  ('TRICEPS_PRESS_M', '트라이셉스 프레스 머신', 'machine', array['machine_triceps_press'], false, 5, '{}', false),
  ('ROTARY_TORSO_M', '로터리 토르소', 'machine', array['machine_torso_rotation'], false, 5, '{}', false),
  ('MULTI_HIP_M', '멀티 힙 머신', 'machine', array['machine_hip_add','machine_hip_abd','machine_glute_kickback'], false, 5, '{}', true)
on conflict (code) do update set
  name_ko = excluded.name_ko,
  category = excluded.category,
  provides = excluded.provides,
  is_generative = excluded.is_generative,
  default_step_kg = excluded.default_step_kg,
  supports_unilateral = excluded.supports_unilateral;

insert into public.exercises
  (code, name_ko, pattern, primary_muscles, secondary_muscles, requires,
   is_freeform, setup_note, is_compound, skill_level, avoid_areas,
   laterality, force_path, substitution_group)
values
  ('MACHINE_LAT_PULLDOWN', '랫 풀다운 머신', 'vertical_pull', array['광배근','이두'], '{}', array['machine_lat_pulldown'], false, null, true, 1, '{}', 'bilateral', 'vertical', 'vertical_pull'),
  ('MACHINE_INCLINE_PRESS', '인클라인 체스트 프레스', 'horizontal_push', array['윗가슴','삼두'], '{}', array['machine_incline_press'], false, null, true, 1, '{}', 'bilateral', 'diagonal', 'horizontal_push'),
  ('MACHINE_DECLINE_PRESS', '디클라인 체스트 프레스', 'horizontal_push', array['아랫가슴','삼두'], '{}', array['machine_decline_press'], false, null, true, 1, '{}', 'bilateral', 'diagonal', 'horizontal_push'),
  ('DB_DECLINE_PRESS', '디클라인 덤벨 프레스', 'horizontal_push', array['아랫가슴','삼두'], '{}', array['dumbbell','bench_decline'], true, null, true, 2, '{}', 'bilateral', null, 'horizontal_push'),
  ('DB_SQUEEZE_PRESS', '덤벨 스퀴즈 프레스', 'horizontal_push', array['가슴','삼두'], '{}', array['dumbbell','bench_flat'], true, null, false, 1, '{}', 'bilateral', null, 'horizontal_push'),
  ('DB_SINGLE_PRESS', '원암 덤벨 벤치프레스', 'horizontal_push', array['가슴','삼두','코어'], '{}', array['dumbbell','bench_flat'], true, null, true, 1, '{}', 'unilateral', null, 'horizontal_push'),
  ('CABLE_SINGLE_PRESS', '원암 케이블 체스트 프레스', 'horizontal_push', array['가슴','삼두','코어'], '{}', array['cable_mid'], true, null, false, 1, '{}', 'unilateral', null, 'horizontal_push'),
  ('CABLE_HIGH_FLY', '하이 투 로우 케이블 플라이', 'horizontal_adduction', array['아랫가슴'], '{}', array['cable_high','cable_dual'], true, null, false, 1, '{}', 'bilateral', 'diagonal', 'horizontal_adduction'),
  ('CABLE_LOW_FLY', '로우 투 하이 케이블 플라이', 'horizontal_adduction', array['윗가슴'], '{}', array['cable_low','cable_dual'], true, null, false, 1, '{}', 'bilateral', 'diagonal', 'horizontal_adduction'),
  ('PUSHUP_INCLINE', '인클라인 푸시업', 'horizontal_push', array['가슴','삼두'], '{}', array['bench_flat'], true, null, true, 1, '{}', 'bilateral', null, 'horizontal_push'),
  ('PUSHUP_DECLINE', '디클라인 푸시업', 'horizontal_push', array['윗가슴','삼두'], '{}', array['bench_flat'], true, null, true, 2, '{}', 'bilateral', null, 'horizontal_push'),
  ('MACHINE_HIGH_ROW', '하이 로우 머신', 'horizontal_pull', array['광배근','능형근','이두'], '{}', array['machine_high_row'], false, null, true, 1, '{}', 'bilateral', 'diagonal', 'horizontal_pull'),
  ('MACHINE_LOW_ROW', '로우 로우 머신', 'horizontal_pull', array['광배근','능형근','이두'], '{}', array['machine_low_row'], false, null, true, 1, '{}', 'bilateral', null, 'horizontal_pull'),
  ('MACHINE_INCLINE_PULL', '인클라인 풀 머신', 'vertical_pull', array['광배근','후면어깨','이두'], '{}', array['machine_incline_pull'], false, null, true, 1, '{}', 'bilateral', 'diagonal', 'vertical_pull'),
  ('MACHINE_PULLOVER', '머신 풀오버', 'vertical_pull', array['광배근','대원근'], '{}', array['machine_pullover'], false, null, false, 1, '{}', 'bilateral', null, 'vertical_pull'),
  ('MACHINE_REAR_DELT', '리어 델트 머신', 'horizontal_abduction', array['후면어깨','능형근'], '{}', array['machine_rear_delt'], false, null, false, 1, '{}', 'bilateral', null, 'horizontal_abduction'),
  ('PENDLAY_ROW', '펜들레이 로우', 'horizontal_pull', array['등','이두'], '{}', array['barbell'], false, null, true, 3, array['low_back'], 'bilateral', null, 'horizontal_pull'),
  ('T_BAR_ROW', '티바 로우', 'horizontal_pull', array['광배근','능형근','이두'], '{}', array['landmine'], false, null, true, 2, '{}', 'bilateral', null, 'horizontal_pull'),
  ('MEADOWS_ROW', '메도우스 로우', 'horizontal_pull', array['광배근','후면어깨'], '{}', array['landmine'], true, null, true, 2, '{}', 'unilateral', null, 'horizontal_pull'),
  ('SEAL_ROW_DB', '덤벨 씰 로우', 'horizontal_pull', array['등','이두'], '{}', array['dumbbell','bench_flat'], true, null, true, 1, '{}', 'bilateral', null, 'horizontal_pull'),
  ('CABLE_ROW_SINGLE', '원암 시티드 케이블 로우', 'horizontal_pull', array['광배근','능형근','이두'], '{}', array['cable_low'], true, null, true, 1, '{}', 'unilateral', null, 'horizontal_pull'),
  ('LAT_PULL_SINGLE', '원암 랫풀다운', 'vertical_pull', array['광배근','이두'], '{}', array['cable_high'], true, null, true, 1, '{}', 'unilateral', null, 'vertical_pull'),
  ('LAT_PULL_UNDER', '언더그립 랫풀다운', 'vertical_pull', array['광배근','이두'], '{}', array['cable_high'], true, null, true, 1, '{}', 'bilateral', null, 'vertical_pull'),
  ('KNEELING_PULLDOWN', '니링 케이블 랫풀다운', 'vertical_pull', array['광배근','코어'], '{}', array['cable_high'], true, null, true, 1, '{}', 'bilateral', null, 'vertical_pull'),
  ('SCAP_PULLUP', '스캡 풀업', 'vertical_pull', array['하부승모근','광배근'], '{}', array['pullup_bar'], true, null, false, 2, '{}', 'bilateral', null, 'vertical_pull'),
  ('ARNOLD_PRESS', '아놀드 프레스', 'vertical_push', array['어깨','삼두'], '{}', array['dumbbell'], true, null, true, 2, '{}', 'bilateral', null, 'vertical_push'),
  ('MACHINE_LATERAL', '머신 래터럴 레이즈', 'abduction', array['측면어깨'], '{}', array['machine_lateral_raise'], false, null, false, 1, '{}', 'bilateral', null, 'abduction'),
  ('CABLE_Y_RAISE', '케이블 Y 레이즈', 'abduction', array['측면어깨','하부승모근'], '{}', array['cable_low','cable_dual'], true, null, false, 1, '{}', 'bilateral', null, 'abduction'),
  ('CABLE_LATERAL_SINGLE', '원암 케이블 래터럴 레이즈', 'abduction', array['측면어깨'], '{}', array['cable_low'], true, null, false, 1, '{}', 'unilateral', null, 'abduction'),
  ('DB_FRONT_RAISE', '덤벨 프론트 레이즈', 'vertical_push', array['전면어깨'], '{}', array['dumbbell'], true, null, false, 1, '{}', 'bilateral', null, 'vertical_push'),
  ('CABLE_REAR_SINGLE', '원암 케이블 리어 델트', 'horizontal_abduction', array['후면어깨'], '{}', array['cable_mid'], true, null, false, 1, '{}', 'unilateral', null, 'horizontal_abduction'),
  ('DB_SHRUG', '덤벨 슈러그', 'carry', array['승모근'], '{}', array['dumbbell'], true, null, false, 1, '{}', 'bilateral', null, 'carry'),
  ('BB_SHRUG', '바벨 슈러그', 'carry', array['승모근'], '{}', array['barbell'], false, null, false, 1, '{}', 'bilateral', null, 'carry'),
  ('PENDULUM_SQUAT_EX', '펜듈럼 스쿼트', 'squat', array['대퇴사두','둔근'], '{}', array['machine_pendulum_squat'], false, null, true, 1, '{}', 'bilateral', null, 'squat'),
  ('BELT_SQUAT_EX', '벨트 스쿼트', 'squat', array['대퇴사두','둔근'], '{}', array['machine_belt_squat'], false, null, true, 1, '{}', 'bilateral', null, 'squat'),
  ('V_SQUAT_EX', 'V 스쿼트', 'squat', array['대퇴사두','둔근'], '{}', array['machine_v_squat'], false, null, true, 2, '{}', 'bilateral', null, 'squat'),
  ('SISSY_SQUAT_EX', '시시 스쿼트 머신', 'extension', array['대퇴사두'], '{}', array['machine_sissy_squat'], false, null, false, 2, array['knee'], 'bilateral', null, 'extension'),
  ('LEG_PRESS_SINGLE', '원레그 프레스', 'squat', array['대퇴사두','둔근'], '{}', array['machine_leg_press'], false, null, true, 1, '{}', 'unilateral', null, 'squat'),
  ('LEG_PRESS_HIGH', '레그프레스 하이 풋', 'squat', array['둔근','햄스트링'], '{}', array['machine_leg_press'], false, '발을 발판 위쪽에 둡니다', true, 1, '{}', 'bilateral', null, 'squat'),
  ('LEG_PRESS_NARROW', '레그프레스 내로우 스탠스', 'squat', array['대퇴사두'], '{}', array['machine_leg_press'], false, '발 간격을 좁게 둡니다', true, 1, '{}', 'bilateral', null, 'squat'),
  ('LEG_EXT_SINGLE', '원레그 익스텐션', 'extension', array['대퇴사두'], '{}', array['machine_leg_ext'], false, null, false, 1, '{}', 'unilateral', null, 'extension'),
  ('LEG_CURL_SEATED', '시티드 레그 컬', 'flexion', array['햄스트링'], '{}', array['machine_leg_curl_seated'], false, null, false, 1, '{}', 'bilateral', null, 'flexion'),
  ('LEG_CURL_PRONE', '라잉 레그 컬', 'flexion', array['햄스트링'], '{}', array['machine_leg_curl_prone'], false, null, false, 1, '{}', 'bilateral', null, 'flexion'),
  ('LEG_CURL_STANDING', '스탠딩 원레그 컬', 'flexion', array['햄스트링'], '{}', array['machine_leg_curl_standing'], false, null, false, 1, '{}', 'unilateral', null, 'flexion'),
  ('GLUTE_KICKBACK_M', '글루트 킥백 머신', 'hinge', array['둔근'], '{}', array['machine_glute_kickback'], false, null, false, 1, '{}', 'unilateral', null, 'hinge'),
  ('HIP_ABD_LEAN', '힙 어브덕션 상체 숙이기', 'abduction', array['중둔근'], '{}', array['machine_hip_abd'], false, '상체를 약간 앞으로 숙입니다', false, 1, '{}', 'bilateral', null, 'abduction'),
  ('HIP_ADD_EX_2', '힙 어덕션', 'adduction', array['내전근'], '{}', array['machine_hip_add'], false, null, false, 1, '{}', 'bilateral', null, 'adduction'),
  ('GOOD_MORNING', '바벨 굿모닝', 'hinge', array['햄스트링','둔근','척추기립근'], '{}', array['barbell','squat_rack'], false, null, true, 3, array['low_back'], 'bilateral', null, 'hinge'),
  ('SUMO_DEADLIFT', '스모 데드리프트', 'hinge', array['둔근','내전근','햄스트링'], '{}', array['barbell'], false, null, true, 3, array['low_back'], 'bilateral', null, 'hinge'),
  ('DB_REVERSE_LUNGE', '덤벨 리버스 런지', 'squat', array['둔근','대퇴사두'], '{}', array['dumbbell'], true, null, true, 1, '{}', 'alternating', null, 'squat'),
  ('SMITH_BULGARIAN', '스미스 불가리안 스플릿 스쿼트', 'squat', array['둔근','대퇴사두'], '{}', array['smith','bench_flat'], false, null, true, 2, '{}', 'unilateral', null, 'squat'),
  ('CABLE_PULLTHROUGH_ALT', '케이블 힙 힌지', 'hinge', array['둔근','햄스트링'], '{}', array['cable_low'], true, '보조 힙힌지 종목', false, 1, '{}', 'bilateral', null, 'hinge'),
  ('MACHINE_PREACHER_CURL', '머신 프리처 컬', 'elbow_flexion', array['이두'], '{}', array['machine_biceps_preacher'], false, null, false, 1, '{}', 'bilateral', null, 'elbow_flexion'),
  ('MACHINE_ARM_CURL', '머신 암 컬', 'elbow_flexion', array['이두'], '{}', array['machine_biceps'], false, null, false, 1, '{}', 'bilateral', null, 'elbow_flexion'),
  ('INCLINE_DB_CURL', '인클라인 덤벨 컬', 'elbow_flexion', array['이두'], '{}', array['dumbbell','bench_incline'], true, null, false, 1, '{}', 'bilateral', null, 'elbow_flexion'),
  ('CONCENTRATION_CURL', '컨센트레이션 컬', 'elbow_flexion', array['이두'], '{}', array['dumbbell','bench_flat'], true, null, false, 1, '{}', 'unilateral', null, 'elbow_flexion'),
  ('BAYESIAN_CURL', '베이지안 케이블 컬', 'elbow_flexion', array['이두'], '{}', array['cable_low'], true, null, false, 1, '{}', 'unilateral', null, 'elbow_flexion'),
  ('REVERSE_CURL', '리버스 컬', 'elbow_flexion', array['상완요골근','이두'], '{}', array['ez_bar'], false, null, false, 1, '{}', 'bilateral', null, 'elbow_flexion'),
  ('MACHINE_ARM_EXT', '머신 암 익스텐션', 'elbow_extension', array['삼두'], '{}', array['machine_triceps_extension'], false, null, false, 1, '{}', 'bilateral', null, 'elbow_extension'),
  ('MACHINE_DIP_PRESS', '머신 딥 프레스', 'elbow_extension', array['삼두','아랫가슴'], '{}', array['machine_dip_press'], false, null, true, 1, '{}', 'bilateral', null, 'elbow_extension'),
  ('MACHINE_TRICEPS_PRESS', '트라이셉스 프레스 머신', 'elbow_extension', array['삼두'], '{}', array['machine_triceps_press'], false, null, false, 1, '{}', 'bilateral', null, 'elbow_extension'),
  ('CABLE_OVERHEAD_ROPE', '로프 오버헤드 트라이셉스 익스텐션', 'elbow_extension', array['삼두'], '{}', array['cable_low'], true, null, false, 1, '{}', 'bilateral', null, 'elbow_extension'),
  ('DB_TRICEPS_KICKBACK', '덤벨 트라이셉스 킥백', 'elbow_extension', array['삼두'], '{}', array['dumbbell'], true, null, false, 1, '{}', 'unilateral', null, 'elbow_extension'),
  ('TORSO_ROTATION_M', '토르소 로테이션 머신', 'rotation', array['복사근','코어'], '{}', array['machine_torso_rotation'], false, null, false, 1, '{}', 'bilateral', 'rotation', 'rotation'),
  ('CABLE_WOODCHOP', '케이블 우드촙', 'rotation', array['복사근','코어'], '{}', array['cable_high'], true, null, false, 1, '{}', 'unilateral', 'diagonal', 'rotation'),
  ('CABLE_REVERSE_WOODCHOP', '리버스 케이블 우드촙', 'rotation', array['복사근','코어'], '{}', array['cable_low'], true, null, false, 1, '{}', 'unilateral', 'diagonal', 'rotation'),
  ('HANGING_KNEE_RAISE', '행잉 니 레이즈', 'core', array['복근','고관절굴곡근'], '{}', array['pullup_bar'], false, null, false, 2, '{}', 'bilateral', null, 'core'),
  ('REVERSE_CRUNCH', '리버스 크런치', 'core', array['복근'], '{}', array['floor_mat'], true, null, false, 1, '{}', 'bilateral', null, 'core'),
  ('SIDE_PLANK', '사이드 플랭크', 'core', array['복사근','코어'], '{}', array['floor_mat'], true, null, false, 1, '{}', 'unilateral', null, 'core'),
  ('SUITCASE_CARRY', '수트케이스 캐리', 'carry', array['코어','전완근'], '{}', array['dumbbell'], true, null, true, 1, '{}', 'unilateral', 'carry', 'carry')
on conflict (code) do update set
  name_ko = excluded.name_ko,
  pattern = excluded.pattern,
  primary_muscles = excluded.primary_muscles,
  requires = excluded.requires,
  is_freeform = excluded.is_freeform,
  setup_note = excluded.setup_note,
  is_compound = excluded.is_compound,
  skill_level = excluded.skill_level,
  avoid_areas = excluded.avoid_areas,
  laterality = excluded.laterality,
  force_path = excluded.force_path,
  substitution_group = excluded.substitution_group;
